# Generated by Django 4.2.4 on 2023-08-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doners',
            new_name='Doner',
        ),
    ]
