# Generated by Django 4.2.4 on 2023-08-30 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_doners_doner'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
